apiVersion: v1
kind: Service
metadata:
  name: triadknox-blend-service
spec:
  type: LoadBalancer
  selector:
    app: triadknox-blend
  ports:
    - protocol: TCP
      port: 80   # Exposed port
      targetPort: 5000  # Port inside the container
